<?php
// module/FBWatch/view/fb-watch/fb-watch/index.phtml:

$title = 'FBWatch Status';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<h2>Add new resource to observe</h2>
<form name="input" action="<?=$this->url('fbwatch', array('action' => 'add'));?>" method="post">
    Facebook URL: <input type="text" id="resource-url" name="resource-url"><br>
    <button class="btn" type="submit">Add</button>
</form>

<h2>Current Resources</h2>
<table class="table">
<tr>
    <th>Name</th>
    <th>Facebook ID</th>
    <th>Active</th>
    <th>Last Synced</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($resources as $resource) : ?>
<tr>
    <td><?php echo $this->escapeHtml($resource->resourceName);?></td>
    <td><?php echo $this->escapeHtml($resource->facebookId);?></td>
    <td><?php echo $this->escapeHtml($resource->active);?></td>
    <td><?php echo $this->escapeHtml($resource->lastSynced);?></td>
    <td>
        <a href="<?php //echo $this->url('album',
            //array('action'=>'edit', 'id' => $resource->id));?>">Edit</a>
        <a href="<?php //echo $this->url('album',
            //array('action'=>'delete', 'id' => $resource->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>